title: 😎
author: Ankit Singh
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It's me here Ankit Singh(ankitzm). I will update this site in near future.

# social links
twitter_username: ankitzm # DO NOT include the @ character, or else the build will fail!
github_username:  ankitzm # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

#theme
theme: minima
